run:
  timeout: 2m
  modules-download-mode: readonly
  dirs:
    - backend/

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
